### ISSUE TITLE
Exception trying to build

### ISSUE THREAD

**Issue by guilhermeolisi** [Projektanker/Icons.Avalonia#28]
Hi,

I cloned your project and tried to build it in VS 2022 but got an exception. Can you help me to resolve this? I don't understand this problem.
Thanks

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'NamespaceInfo:/App.xaml' threw an exception.
  Source=Avalonia.IconPacks
  StackTrace:
   at Avalonia.IconPacks.App.!XamlIlPopulate(IServiceProvider , App ) in C:\Users\guilh\Documents\Acadêmico\VisualStudio\AvaloniaIconPacks\src\Avalonia.IconPacks\App.xaml:line 1
   at Avalonia.IconPacks.App.!XamlIlPopulateTrampoline(App )
   at Avalonia.IconPacks.App.Initialize() in C:\Users\guilh\Documents\Acadêmico\VisualStudio\AvaloniaIconPacks\src\Avalonia.IconPacks\App.xaml.cs:line 12
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Avalonia.IconPacks.Program.Main(String[] args) in C:\Users\guilh\Documents\Acadêmico\VisualStudio\AvaloniaIconPacks\src\Avalonia.IconPacks\Program.cs:line 19

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
BadImageFormatException: No string associated with token. The format of the file 'C:\Users\guilh\Documents\Acadêmico\VisualStudio\AvaloniaIconPacks\src\Avalonia.IconPacks\bin\x64\Debug\net6.0\Avalonia.IconPacks.dll' is invalid.

**Comment by SebastianRumohr** [comment]
I can't find any class in the stack trace that is inside the `Projektanker.Icons.Avalonia` namespace. Are you're you just cloned the project and tried to build it?

**Comment by SebastianRumohr** [comment]
Or did you perhaps cloned this project?
https://github.com/ahopper/Avalonia.IconPacks

**Comment by guilhermeolisi** [comment]
I am sorry, I posted this issue in wrong project. It is possible delete this post?

**Comment by SebastianRumohr** [comment]
No worries 🙂 I'll close the issue.
