### ISSUE TITLE
Not compatible with the v11 release candidate (11.0.0-rc1.1)

### ISSUE THREAD

**Issue by SparkyTD** [Projektanker/Icons.Avalonia#36]
The very first Avalonia v11 release candidate was released yesterday, and it seems to have implemented some breaking changes that break this package completely.  It worked without any issues on the previous v11 preview (11.0.0-preview8).

Here's the exception that is thrown when I try to use your library in a simple test app with the rc1.1 version of Avalonia:
```
Unhandled exception. System.TypeLoadException: Could not load type 'Avalonia.Data.TemplateBinding' from assembly 'Avalonia.Markup, Version=11.0.0.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'.
   at Projektanker.Icons.Avalonia.Icon.XamlClosure_1.Build(IServiceProvider)
   at Avalonia.Markup.Xaml.XamlIl.Runtime.XamlIlRuntimeHelpers.<>c__DisplayClass1_0`1.DeferredTransformationFactoryV2>b__0(IServiceProvider sp) in /_/src/Markup/Avalonia.Markup.Xaml/XamlIl/Runtime/XamlIlRuntimeHe
lpers.cs:line 34
   at Avalonia.Markup.Xaml.Templates.TemplateContent.Load(Object templateContent) in /_/src/Markup/Avalonia.Markup.Xaml/Templates/TemplateContent.cs:line 13
   at Avalonia.Markup.Xaml.Templates.ControlTemplate.Build(TemplatedControl control) in /_/src/Markup/Avalonia.Markup.Xaml/Templates/ControlTemplate.cs:line 17
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate() in /_/src/Avalonia.Controls/Primitives/TemplatedControl.cs:line:289
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 529
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 373
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 47
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 583
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 541
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 373
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Base/Layout/LayoutHelper.cs:line 63
   at Avalonia.Controls.Decorator.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Decorator.cs:line 54
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Primitives/VisualLayerManager.cs:line 139
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 541
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 373
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 608
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 541
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 373
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 608
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Window.cs:line 923
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) in /_/src/Avalonia.Controls/WindowBase.cs:line 274
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Base/Layout/Layoutable.cs:line 373
   at Avalonia.Layout.LayoutManager.Measure(Layoutable control) in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 304
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() in /_/src/Avalonia.Base/Layout/LayoutManager.cs:line 191
   at Avalonia.Controls.Window.ShowCore(Window owner) in /_/src/Avalonia.Controls/Window.cs:line 706
   at Avalonia.Controls.Window.Show() in /_/src/Avalonia.Controls/Window.cs:line 601
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow() in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 136
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 125
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/Classi
cDesktopStyleApplicationLifetime.cs:line 220

```

**Comment by cyraid** [comment]
I cloned it locally, and changed it to include 11 (as it was including version 10). If you also include Avalonia.ReactiveUI it gets rid of a small error, but it can't seem to find AppBuilderBase..

**Comment by SebastianRumohr** [comment]
⚠️ The registration changed. You have to register the icon provider directly with the `IconProvider.Current`.
See here: https://github.com/Projektanker/Icons.Avalonia/tree/avalonia-11-preview#1-register-icon-providers-on-app-start-up
